# Generated by Django 5.0.4 on 2024-04-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dam', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
